# Default initial positions for gen3's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  joint_7: 0
  robotiq_85_left_knuckle_joint: 0
